<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">
<!--<!DOCTYPE students [-->
<!--		<!ELEMENT students (student*) >-->
<!--		<!ELEMENT student (name,age,sex)>-->
<!--		<!ELEMENT name (#PCDATA)>-->
<!--		<!ELEMENT age (#PCDATA)>-->
<!--		<!ELEMENT sex (#PCDATA)>-->
<!--		<!ATTLIST student number ID #REQUIRED>-->
<!--		]>-->
<students>
	<student number="t1">
		<name>tom</name>
		<age>18</age>
		<sex>male</sex>
	</student>
	<student number="t2">
		<name>cat</name>
		<age>20</age>
		<sex>female</sex>
	</student>
</students>